name: LethalSnow
version: 0.50
description: Changes snowball damage, and can add more exhaustion while in snow biomes.
main: com.foocraft.LeathalSnow.LethalSnow
author: LordJason
website: http://dev.bukkit.org/server-mods/lethalsnow/ - http://foocraft.com
database: false

commands:
  lsnow:
    description: Lethalsnow primary command.
    aliases: [lethalsnow]
    permission: lethalsnow.use
    usage: "Usage\n------------------\n/<command> (min/max/chance/exhaustion) (0-100)\n/<command> (damageplayer/damagemob) (true/false)\n/<command> reload\n/<command> biome\n------------------"
permissions:
    lethalsnow.use:
        description: allows usage of the lethalsnow command.
        default: op